/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajopractico5;

import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author santiago10
 */
public class BuscarClienteVista extends javax.swing.JInternalFrame {
    
    

    /**
     * Creates new form BuscarClienteVista
     */
    public BuscarClienteVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTBTelefono = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JBSalir = new javax.swing.JButton();
        JTBDNI = new javax.swing.JTextField();
        JTBApellido = new javax.swing.JTextField();
        JTBNombre = new javax.swing.JTextField();
        JTBCiudad = new javax.swing.JTextField();
        JTBDomicilio = new javax.swing.JTextField();
        JTBBuscar = new javax.swing.JToggleButton();

        jLabel1.setText("Telefono");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Busqueda de Clientes");

        JTBTelefono.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                JTBTelefonoCaretUpdate(evt);
            }
        });
        JTBTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTBTelefonoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTBTelefonoKeyReleased(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField2CaretUpdate(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("DNI:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Nombre:");

        jLabel6.setText("Ciudad");

        jLabel7.setText("Domicilio");

        JBSalir.setText("Salir");
        JBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalirActionPerformed(evt);
            }
        });

        JTBDNI.setEditable(false);

        JTBApellido.setEditable(false);

        JTBNombre.setEditable(false);

        JTBCiudad.setEditable(false);

        JTBDomicilio.setEditable(false);

        JTBBuscar.setText("Buscar");
        JTBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(JTBTelefono))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTBDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(JTBCiudad)
                            .addComponent(JTBNombre)
                            .addComponent(JTBApellido)
                            .addComponent(JTBDNI))
                        .addGap(0, 72, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(JTBBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBSalir)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTBTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(JTBDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JTBApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(JTBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(JTBCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(JTBDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBSalir)
                    .addComponent(JTBBuscar))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void JBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalirActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_JBSalirActionPerformed

    private void JTBTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTBTelefonoKeyPressed
                 // TODO add your handling code here:
    }//GEN-LAST:event_JTBTelefonoKeyPressed

    private void JTBTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTBTelefonoKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_JTBTelefonoKeyReleased

    private void JTBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBBuscarActionPerformed
            
        
        
        Long aux = Long.parseLong(jTextField2.getText());
                
                Contacto contactoAux = DirectorioTelefonico.ListaDeContactos.get(aux);
                
                JTBNombre.setText(contactoAux.getNombre());
                JTBApellido.setText(contactoAux.getApellido());
                JTBDNI.setText(contactoAux.getDNI()+"");
                JTBDomicilio.setText(contactoAux.getDireccion());
                JTBCiudad.setText(contactoAux.getCiudad());
        
        /* String texto = JTBTelefono.getText();
        
         if(!texto.isEmpty()){
         
            for (Map.Entry<Long, Contacto> entry : DirectorioTelefonico.ListaDeContactos.entrySet() ){
               
                if(String.valueOf(entry.getKey()).startsWith(texto)){
                    jTextField2.setText(String.valueOf(entry.getKey()));
                    break;
                }
            
            }
        
        }else{
             jTextField2.setText("");
         }
        
        
        */
        
// TODO add your handling code here:
    }//GEN-LAST:event_JTBBuscarActionPerformed

    private void jTextField2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField2CaretUpdate
                
               /* Long aux = Long.parseLong(jTextField2.getText());
                
                Contacto contactoAux = DirectorioTelefonico.ListaDeContactos.get(aux);
                
                JTBNombre.setText(contactoAux.getNombre());
                JTBApellido.setText(contactoAux.getApellido());
                JTBDNI.setText(contactoAux.getDNI()+"");
                JTBDomicilio.setText(contactoAux.getDireccion());
                JTBCiudad.setText(contactoAux.getCiudad());
                
        */
        
                // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2CaretUpdate

    private void JTBTelefonoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_JTBTelefonoCaretUpdate
         String texto = JTBTelefono.getText();
        
         if(!texto.isEmpty()){
         
            for (Map.Entry<Long, Contacto> entry : DirectorioTelefonico.ListaDeContactos.entrySet() ){
               
                if(String.valueOf(entry.getKey()).startsWith(texto)){
                    jTextField2.setText(String.valueOf(entry.getKey()));
                    break;
                }
            
            }
        
        }else{
             jTextField2.setText("");
         }           // TODO add your handling code here:
    }//GEN-LAST:event_JTBTelefonoCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBSalir;
    private javax.swing.JTextField JTBApellido;
    private javax.swing.JToggleButton JTBBuscar;
    private javax.swing.JTextField JTBCiudad;
    private javax.swing.JTextField JTBDNI;
    private javax.swing.JTextField JTBDomicilio;
    private javax.swing.JTextField JTBNombre;
    private javax.swing.JTextField JTBTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
